
package org.edwintumax.client.core.sw;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AlumnoServiceWSImplService", targetNamespace = "http://service.core.edwintumax.org/", wsdlLocation = "http://DESKTOP-BBT8AIT:9090/AlumnoServiceWSImplService/AlumnoServiceWSImpl?wsdl")
public class AlumnoServiceWSImplService
    extends Service
{

    private final static URL ALUMNOSERVICEWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ALUMNOSERVICEWSIMPLSERVICE_EXCEPTION;
    private final static QName ALUMNOSERVICEWSIMPLSERVICE_QNAME = new QName("http://service.core.edwintumax.org/", "AlumnoServiceWSImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://DESKTOP-BBT8AIT:9090/AlumnoServiceWSImplService/AlumnoServiceWSImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ALUMNOSERVICEWSIMPLSERVICE_WSDL_LOCATION = url;
        ALUMNOSERVICEWSIMPLSERVICE_EXCEPTION = e;
    }

    public AlumnoServiceWSImplService() {
        super(__getWsdlLocation(), ALUMNOSERVICEWSIMPLSERVICE_QNAME);
    }

    public AlumnoServiceWSImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ALUMNOSERVICEWSIMPLSERVICE_QNAME, features);
    }

    public AlumnoServiceWSImplService(URL wsdlLocation) {
        super(wsdlLocation, ALUMNOSERVICEWSIMPLSERVICE_QNAME);
    }

    public AlumnoServiceWSImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ALUMNOSERVICEWSIMPLSERVICE_QNAME, features);
    }

    public AlumnoServiceWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AlumnoServiceWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AlumnoServiceWS
     */
    @WebEndpoint(name = "AlumnoServiceWSImplPort")
    public AlumnoServiceWS getAlumnoServiceWSImplPort() {
        return super.getPort(new QName("http://service.core.edwintumax.org/", "AlumnoServiceWSImplPort"), AlumnoServiceWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AlumnoServiceWS
     */
    @WebEndpoint(name = "AlumnoServiceWSImplPort")
    public AlumnoServiceWS getAlumnoServiceWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.core.edwintumax.org/", "AlumnoServiceWSImplPort"), AlumnoServiceWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ALUMNOSERVICEWSIMPLSERVICE_EXCEPTION!= null) {
            throw ALUMNOSERVICEWSIMPLSERVICE_EXCEPTION;
        }
        return ALUMNOSERVICEWSIMPLSERVICE_WSDL_LOCATION;
    }

}
